generic-service:
  nameOverride: hmpps-electronic-monitoring-crime-matching-ui
  productId: 'HMPPS549' # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  # the IRSA service account name for accessing AWS resources
  # serviceAccountName: "hmpps-electronic-monitoring-crime-matching-ui"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-electronic-monitoring-crime-matching-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-electronic-monitoring-crime-matching-ui-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'HMPPS549' # Your audit service name
    OS_MAPS_AUTH_URL: "https://api.os.uk/oauth2/token/v1"
    OS_MAPS_TILE_URL: "https://api.os.uk/maps/raster/v1/zxy/Road_3857/{z}/{x}/{y}"
    OS_MAPS_VECTOR_URL: "https://api.os.uk/maps/vector/v1/vts/resources/styles?srs=3857"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    # These secrets are created by terraform.
    hmpps-electronic-monitoring-crime-matching-ui-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    hmpps-electronic-monitoring-crime-matching-ui-auth-code:
      AUTH_CODE_CLIENT_ID: 'AUTH_CODE_CLIENT_ID'
      AUTH_CODE_CLIENT_SECRET: 'AUTH_CODE_CLIENT_SECRET'
    hmpps-electronic-monitoring-crime-matching-ui-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'
    hmpps-electronic-monitoring-crime-matching-ui-elasticache-redis:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    hmpps-electronic-monitoring-crime-matching-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    # This secret will need to be created in your namespace (note it isn't in hmpps-templates-dev)
    # IRSA configuration in your namespace will also be required, and then uncomment serviceAccountName above.
    # sqs-hmpps-audit-secret:
    #   AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'    
    hmpps-electronic-monitoring-crime-matching-os-maps:
      OS_MAPS_API_KEY: 'OS_MAPS_API_KEY'
      OS_MAPS_API_SECRET: 'OS_MAPS_API_SECRET'

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-electronic-monitoring-crime-matching-ui

# Whether to deploy the stubs
# Override in values-dev.yaml
# Also update the environment variables to point the application to the mocked services (on port 80)
deploy_stubs: false

