---
# Per environment values which override defaults in hmpps-electronic-monitoring-crime-matching-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: electronic-monitoring-crime-matching-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://electronic-monitoring-crime-matching-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    EM_CRIME_MATCHING_API_URL: "http://hmpps-electronic-monitoring-crime-matching-api-stubs/crime-matching"

generic-prometheus-alerts:
  alertSeverity: na

deploy_stubs: true
