---
# Per environment values which override defaults in hmpps-electronic-monitoring-crime-matching-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: electronic-monitoring-crime-matching-ui-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://electronic-monitoring-crime-matching-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"
    OS_MAPS_AUTH_URL: "https://api.os.uk/oauth2/token/v1"
    OS_MAPS_TILE_URL: "https://api.os.uk/maps/raster/v1/zxy/Road_3857/{z}/{x}/{y}"

generic-prometheus-alerts:
  alertSeverity: na
