const ROLE_CRIME_MATCHING_HUB_CASEWORKER = 'ROLE_CRIME_MATCHING_HUB_CASEWORKER' as const
const ROLE_CRIME_MATCHING_HUB_MANAGER = 'ROLE_CRIME_MATCHING_HUB_MANAGER' as const

const CRIME_MATCHING_ROLES = [ROLE_CRIME_MATCHING_HUB_CASEWORKER, ROLE_CRIME_MATCHING_HUB_MANAGER]

export { CRIME_MATCHING_ROLES, ROLE_CRIME_MATCHING_HUB_CASEWORKER, ROLE_CRIME_MATCHING_HUB_MANAGER }
