const ROLES = {
  CRIME_MATCHING_HUB_CASEWORKER: 'CRIME_MATCHING_HUB_CASEWORKER',
  CRIME_MATCHING_HUB_MANAGER: 'CRIME_MATCHING_HUB_MANAGER',
} as const

type Role = keyof typeof ROLES

const CRIME_MATCHING_ROLES = Object.keys(ROLES)

export { CRIME_MATCHING_ROLES, ROLES, Role }
