name: Test - nunjucks format

on:
  workflow_call:
    inputs:
      node_version_file:
        description: "Passed to setup-node action to specify where to source the version of node from"
        required: false
        type: string
        default: ".nvmrc"

permissions:
  contents: read

jobs:
  nunjucks_format:
    name: Check nunjucks files are formatted correctly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node_version_file }}
      - name: update npm
        shell: bash
        run: |
          sudo npm install -g npm@latest
      - name: restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        env: 
          cache-name: node-modules
        with:
          path: |
            ./node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }} 
      - name: install dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          npm ci --no-audit
      - name: check nunjucks file formatting
        shell: bash
        run: |
          npx prettier server/**/*.njk --check
